POST http://localhost:3000/api/newUser
Content-Type: application/application/json

{
    "Name":"Kittu",
    "PhoneNumber":4567891230,
    "EmailAddress":"kccodes254@gmail.com",
    "Password":"NOPASSWORD"
}
